# Generated by Django 3.0.2 on 2021-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
